---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[python::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
